<?php

/**
 * @file
 * Drupal Module: Quantcast
 *
 * Provides integration with Quantcast.com media measurement and web analytics service.
 *
 * @Author: Irakli Nadareishvili. <a href="http://phase2technology.com">Phase2 Technology</a>
 *          Drupal 7 implementation, refactoring and new features by Maciej Zgadzaj (http://zgadzaj.com/)
 */


/**
 * Implementation of hook_help().
 */
function quantcast_help($path, $arg) {
  switch ($path) {
    case 'admin/config/system/quantcast':
      return t('<a href="@qc_url">Quantcast</a> is a free (registration required) media measurement and web analytics service that allows users to view audience statistics for millions of websites.', array('@qc_url' => 'http://www.quantcast.com/'));
  }
}

/**
 * Implementation of hook_perm().
 */
function quantcast_perm() {
  return array('administer quantcast');
}

/**
 * Implementation of hook_menu().
 */
function quantcast_menu() {
  $items['admin/settings/quantcast'] = array(
    'title'             => 'Quantcast',
    'description'       => 'Configure settings for the quantcast module.',
    'page callback'     => 'drupal_get_form',
    'page arguments'    => array('quantcast_admin_settings_form'),
    'access arguments'  => array('administer quantcast'),
    'file'              => 'quantcast.admin.inc',
    'type'              => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Implementation of hook_theme().
 */
function quantcast_theme() {
  $path = drupal_get_path('module', 'quantcast');
  return array(
    'quantcast_tag_full' => array(
      'template'  => 'quantcast-tag-full',
      'path'      => "$path/theme",
      'arguments' => array('vars' => NULL),
    ),
    'quantcast_tag_head' => array(
      'template'  => 'quantcast-tag-head',
      'path'      => "$path/theme",
      'arguments' => array('vars' => NULL),
    ),
    'quantcast_tag_body' => array(
      'template'  => 'quantcast-tag-body',
      'path'      => "$path/theme",
      'arguments' => array('vars' => NULL),
    ),
  );
}

/**
 * Implementation of template_preprocess_page().
 */
function quantcast_preprocess_page(&$variables) {
  $qacct = variable_get('quantcast_account', '');
  if (!empty($qacct)) {
    $scope = variable_get('quantcast_js_scope', 'closure');
    $vars = array(
      'pcode' => variable_get('quantcast_account', ''),
    );
    if ($scope == 'split') {
      $variables['head'] .= theme('quantcast_tag_head', $vars);
      $variables['closure'] .= theme('quantcast_tag_body', $vars);
    }
    else {
      $variables[$scope] .= theme('quantcast_tag_full', $vars);
    }
  }
}
